import { useState } from "react";
import type { AdminStaffMember } from "../../api";
import { createDailyRecord, recordDailyAction, saveDailyRecord, type DailyRecord } from "../api";
import { StaffPicker } from "../roster/StaffPicker";
import { DailyEditorHeader } from "../shared/DailyEditorHeader";
import type { EditorSaveState } from "../shared/SaveState";
import { saveStateForError } from "../shared/saveStateForError";
import { useDailyAutosave } from "../shared/useDailyAutosave";
import { createEmptyRandomSearchPayload, parseRandomSearchPayload, SEARCH_SECTIONS, type RandomSearchPayload } from "./model";
import { RandomSearchesPrint } from "./RandomSearchesPrint";
import "./searches.css";
interface Props { workDate: string; shift: string; record: DailyRecord | null; onRecordChange: (record: DailyRecord) => void; searchStaff?: (query: string) => Promise<AdminStaffMember[]>; }
export function RandomSearchesEditor({ workDate, shift, record, onRecordChange, searchStaff }: Props) {
  const [payload, setPayload] = useState<RandomSearchPayload>(record ? parseRandomSearchPayload(record.payload) : createEmptyRandomSearchPayload(workDate, shift)); const [saveState, setSaveState] = useState<EditorSaveState>(record ? "saved" : "unsaved"); const [error, setError] = useState<string | null>(null); const [preview, setPreview] = useState(false);
  function update(sectionIndex: number, blockIndex: number, values: Partial<RandomSearchPayload["sections"][number]["blocks"][number]>) { setPayload((current) => ({ ...current, sections: current.sections.map((section, index) => index !== sectionIndex ? section : { ...section, blocks: section.blocks.map((block, itemIndex) => itemIndex === blockIndex ? { ...block, ...values } : block) }) })); setSaveState("unsaved"); }
  async function save(reason: "manual_save" | "autosave" = "manual_save") { setSaveState("saving"); setError(null); try { const saved = record ? await saveDailyRecord({ kind: "random_search_log", recordId: record.recordId, workDate, shift, revision: record.revision, payload, reason }) : await createDailyRecord({ kind: "random_search_log", workDate, shift, payload }); setPayload(parseRandomSearchPayload(saved.payload)); setSaveState("saved"); onRecordChange(saved); } catch (reason) { setSaveState(saveStateForError(reason)); setError(reason instanceof Error ? reason.message : "The Random Searches Log could not be saved."); } }
  useDailyAutosave({ enabled: Boolean(record), dirty: saveState === "unsaved", onSave: () => { void save("autosave"); } });
  async function showPreview() { if (record) await recordDailyAction("random_search_log", record.recordId, "preview"); setPreview(true); } async function print() { if (record) await recordDailyAction("random_search_log", record.recordId, "print"); window.print(); }
  return <div className="searches-workspace"><DailyEditorHeader title="Random Searches Log" workDate={workDate} shift={shift} saveState={saveState} onSave={() => void save()} onPreview={() => void showPreview()} onPrint={() => void print()} saveLabel="Save random searches" />{error ? <div role="alert" className="admin-alert error">{error}</div> : null}<nav className="search-section-nav" aria-label="Random search sections">{SEARCH_SECTIONS.map((section) => <a key={section.code} href={`#search-${section.code}`}>{section.label}</a>)}</nav><div className="search-section-stack">{payload.sections.map((section, sectionIndex) => <section id={`search-${section.section_code}`} key={section.section_code}><h2>{SEARCH_SECTIONS[sectionIndex].label}</h2><div>{section.blocks.map((block, blockIndex) => <article key={blockIndex} data-testid="random-search-block"><h3>Search {blockIndex + 1}</h3><label>Officer<StaffPicker label="Officer" value={block.officer} state={block.officer ? "assigned" : "unassigned"} onChange={(officer) => update(sectionIndex, blockIndex, { officer })} searchStaff={searchStaff} /></label><div><label>Date<input aria-label="Date" type="date" value={block.search_date ?? ""} onChange={(event) => update(sectionIndex, blockIndex, { search_date: event.target.value || null })} /></label><label>Time<input aria-label="Time" type="time" step="1" value={block.search_time ?? ""} onChange={(event) => update(sectionIndex, blockIndex, { search_time: event.target.value || null })} /></label></div><label>Individual Last Name<input aria-label="Individual Last Name" maxLength={160} value={block.individual_last_name} onChange={(event) => update(sectionIndex, blockIndex, { individual_last_name: event.target.value })} /></label><label>Individual Number<input aria-label="Individual Number" maxLength={64} value={block.individual_number} onChange={(event) => update(sectionIndex, blockIndex, { individual_number: event.target.value })} /></label><label>Barracks / Rack<input aria-label="Barracks / Rack" maxLength={160} value={block.barracks_rack} onChange={(event) => update(sectionIndex, blockIndex, { barracks_rack: event.target.value })} /></label><label>Contraband Found and Disposition<textarea aria-label="Contraband Found and Disposition" maxLength={2000} value={block.contraband_disposition} onChange={(event) => update(sectionIndex, blockIndex, { contraband_disposition: event.target.value })} /></label></article>)}</div></section>)}</div><RandomSearchesPrint payload={payload} />{preview ? <div className="search-preview-overlay" role="dialog" aria-modal="true" aria-label="Random Searches print preview"><button onClick={() => setPreview(false)}>Close preview</button><RandomSearchesPrint payload={payload} /></div> : null}</div>;
}
