"""Deterministic form catalog and incident paperwork services."""

from backend.forms.catalog import (
    CatalogConfigurationError,
    FormTemplateDefinition,
    load_form_catalog,
    sync_form_catalog,
)
from backend.forms.packets import (
    IncidentPacketItemView,
    PacketConfigurationError,
    PacketMutationNotAllowed,
    PacketNotFound,
    PacketRevisionConflict,
    PlannedPacketItem,
    add_additional_form,
    build_incident_packet,
    list_incident_packet,
    mark_not_applicable,
    plan_incident_packet,
    remove_recommended_form,
)
from backend.forms.population import (
    FormCompleteness,
    FormInstanceView,
    FormPopulationConfigurationError,
    FormPopulationNotAllowed,
    FormPopulationNotFound,
    FormPopulationNotReady,
    FormPreviewView,
    calculate_form_completeness,
    populate_form_instance,
    render_form_preview,
    resolve_form_fields,
)

__all__ = [
    "CatalogConfigurationError",
    "FormCompleteness",
    "FormInstanceView",
    "FormPopulationConfigurationError",
    "FormPopulationNotAllowed",
    "FormPopulationNotFound",
    "FormPopulationNotReady",
    "FormPreviewView",
    "FormTemplateDefinition",
    "IncidentPacketItemView",
    "PacketConfigurationError",
    "PacketMutationNotAllowed",
    "PacketNotFound",
    "PacketRevisionConflict",
    "PlannedPacketItem",
    "add_additional_form",
    "build_incident_packet",
    "calculate_form_completeness",
    "list_incident_packet",
    "load_form_catalog",
    "mark_not_applicable",
    "plan_incident_packet",
    "populate_form_instance",
    "remove_recommended_form",
    "render_form_preview",
    "resolve_form_fields",
    "sync_form_catalog",
]
