"""Deterministic form catalog and incident paperwork services."""

from backend.forms.catalog import (
    CatalogConfigurationError,
    FormTemplateDefinition,
    load_form_catalog,
    sync_form_catalog,
)
from backend.forms.output_events import (
    DocumentActionEventView,
    DocumentActionNotAllowed,
    DocumentActionNotFound,
    allowed_form_actions,
    allowed_report_actions,
    record_document_action,
    validate_form_action,
    validate_report_action,
)
from backend.forms.packets import (
    IncidentPacketItemView,
    PacketConfigurationError,
    PacketMutationNotAllowed,
    PacketNotFound,
    PacketRevisionConflict,
    PlannedPacketItem,
    add_additional_form,
    build_incident_packet,
    list_incident_packet,
    mark_not_applicable,
    plan_incident_packet,
    remove_recommended_form,
)
from backend.forms.physical import (
    PhysicalPaperworkAcknowledgmentView,
    PhysicalPaperworkNotAllowed,
    PhysicalPaperworkNotFound,
    acknowledge_physical_paperwork,
    clear_physical_acknowledgment,
)
from backend.forms.population import (
    FormCompleteness,
    FormInstanceView,
    FormPopulationConfigurationError,
    FormPopulationNotAllowed,
    FormPopulationNotFound,
    FormPopulationNotReady,
    FormPreviewView,
    calculate_form_completeness,
    populate_form_instance,
    render_form_preview,
    resolve_form_fields,
)

__all__ = [
    "CatalogConfigurationError",
    "DocumentActionEventView",
    "DocumentActionNotAllowed",
    "DocumentActionNotFound",
    "FormCompleteness",
    "FormInstanceView",
    "FormPopulationConfigurationError",
    "FormPopulationNotAllowed",
    "FormPopulationNotFound",
    "FormPopulationNotReady",
    "FormPreviewView",
    "FormTemplateDefinition",
    "IncidentPacketItemView",
    "PacketConfigurationError",
    "PacketMutationNotAllowed",
    "PacketNotFound",
    "PacketRevisionConflict",
    "PhysicalPaperworkAcknowledgmentView",
    "PhysicalPaperworkNotAllowed",
    "PhysicalPaperworkNotFound",
    "PlannedPacketItem",
    "acknowledge_physical_paperwork",
    "add_additional_form",
    "allowed_form_actions",
    "allowed_report_actions",
    "build_incident_packet",
    "calculate_form_completeness",
    "clear_physical_acknowledgment",
    "list_incident_packet",
    "load_form_catalog",
    "mark_not_applicable",
    "plan_incident_packet",
    "populate_form_instance",
    "record_document_action",
    "remove_recommended_form",
    "render_form_preview",
    "resolve_form_fields",
    "sync_form_catalog",
    "validate_form_action",
    "validate_report_action",
]
